apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: inferencing-postgres
spec:
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi9-2.56.0-2547
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 4Gi
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi9-17.7-2547
  instances:
  - dataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 4Gi
    name: instance1
    replicas: 1
    resources:
      limits:
        hugepages-2Mi: 500Mi
        memory: 500Mi
  port: 5432
  postgresVersion: 17
  monitoring:
    pgmonitor:
      exporter:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi9-0.18.1-2547
  users:
  - name: transformer-admin
    databases:
    - scale-inference
    options: SUPERUSER
    password:
      type: AlphaNumeric
