inferenceService:
  enabled: true
  minReplicas: 1
  stopped: false

ui:
  enabled: false
  image: europe-west3-docker.pkg.dev/prokube/development/clef-tetris-ui@sha256:009a1dea1fd1f7a061c681d1a66838d4feeed863391d544282ca9952a3cd2617
  policy: ""
  gateway: kubeflow/kubeflow-gateway
  host: "*"
  path: /clef-flash-demo

monitoring:
  enabled: false
  prometheusRelease: kube-prometheus-stack
  interval: 15s
  dashboardNamespace: ""
