inferenceService:
  enabled: true
  minReplicas: 1
  stopped: false

ui:
  enabled: false
  image: europe-west3-docker.pkg.dev/prokube/development/clef-tetris-ui@sha256:899c623a1a8ee85bbdc4ade0043e1c5810754d8fcc6f2dc7993325231f13e837
  policy: ""
  gateway: kubeflow/kubeflow-gateway
  host: "*"
  path: /clef-flash-demo

monitoring:
  enabled: false
  prometheusRelease: kube-prometheus-stack
  interval: 15s
  dashboardNamespace: ""
