inferenceService:
  enabled: true
  minReplicas: 1
  stopped: false

ui:
  enabled: false
  image: europe-west3-docker.pkg.dev/prokube/development/clef-tetris-ui@sha256:68db9ea460ce98aa436478e208c13addd7be7d169b651881ac7be4473a40cc6a
  policy: ""
  gateway: kubeflow/kubeflow-gateway
  host: "*"
  path: /clef-flash-demo

monitoring:
  enabled: false
  prometheusRelease: kube-prometheus-stack
  interval: 15s
  dashboardNamespace: ""
