"""
Feast feature definitions for the driver stats example.

This file defines:
- An entity (driver_id) identifying what we're tracking features for
- A data source (parquet file with historical driver data)
- A feature view (driver_hourly_stats) with three features

To register these with the Feast registry:
    feast apply

To materialize features to the online store:
    feast materialize-incremental $(date -u +"%Y-%m-%dT%H:%M:%S")
"""

from datetime import timedelta

from feast import Entity, FeatureView, Field, FileSource
from feast.types import Float32, Int64

# Entity: the "primary key" for feature lookups.
# When you request features, you provide entity values (e.g. driver_id=1001).
driver = Entity(
    name="driver_id",
    description="Unique driver identifier",
)

# Data source: where historical feature data lives.
# This parquet file is generated by the notebook example.
driver_stats_source = FileSource(
    path="data/driver_stats.parquet",
    timestamp_field="event_timestamp",
    created_timestamp_column="created",
)

# Feature view: a logical group of features from one data source.
# - `ttl` controls how stale a feature can be before it's considered expired
# - `online=True` means features are materialized to the online store
driver_hourly_stats = FeatureView(
    name="driver_hourly_stats",
    entities=[driver],
    ttl=timedelta(days=7),
    schema=[
        Field(name="conv_rate", dtype=Float32),
        Field(name="acc_rate", dtype=Float32),
        Field(name="avg_daily_trips", dtype=Int64),
    ],
    source=driver_stats_source,
    online=True,
)
