apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: time
spec:
  image: docker.io/mcp/time:latest@sha256:9c46a918633fb474bf8035e3ee90ebac6bcf2b18ccb00679ac4c179cba0ebfcf
  transport: stdio
  proxyPort: 8080
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
            readOnlyRootFilesystem: false
